### ISSUE TITLE
Rubocop: FrozenStringLiteralComment

### ISSUE THREAD

**Issue by stefanroex** [brightin/brightin-template#9]
Ruby 2.3.0 adds a magic comment that indicates that the file can safely have its string literals frozen. Rubocop has a check for that comment called `FrozenStringLiteralComment` and is enabled by default.

Do we keep the default or disable it?

**Comment by avdgaag** [comment]
What do you propose? Care to create a PR?

**Comment by stefanroex** [comment]
I'd like some thoughts: do you think it's fine to keep the default or should we disable it. I've disabled it in my projects, but I don't have any strong opinions about it and would like to decide the default setting for Brightin.

**Comment by avdgaag** [comment]
Let's turn it off by default then, until we have a strong opinion towards turning it on.
